### ISSUE TITLE
http://progettofreecs.altervista.org/ now needs username/password

### ISSUE THREAD

**Issue by Stufo76** [FrancYescO/FreeCSd#1]
http://progettofreecs.altervista.org/ now needs username/password and seems don't allowing some form of registration or so on.

**Comment by joeblackmac** [comment]
Ciao
complimenti sinceri per il tuo progetto freecsD.
Sono anni che lo uso e veramente strabiliante la tua bravura. 
Ti scrivo per sapere se posso avere le credenziali di accesso username/password .
Nel mio tempo libero sono sempre alla ricerca di nuovi siti per le cline free. 
Ogni tanto ne trovo qualcuno stabile che ti vorrei segnalare per aggiornare la lista dei servers stable.
Grazie 
Giovanni

**Comment by FrancYescO** [comment]
@joeblackmac per richiedere l'account puoi far riferimento a questo topic 
http://www.cardsharing.ws/cardsharing/showthread.php/207027-regole-e-richiesta-account-su-progettofreecs-non-scrivete-inutilmente-!

**Comment by carloda** [comment]
Salve ragazzi, il link non è più disponibile o sbaglio?

**Comment by FrancYescO** [comment]
http://www.csws.tk/cardsharing/showthread.php/207027-regole-e-richiesta-account-su-progettofreecs-non-scrivete-inutilmente-!

**Comment by carloda** [comment]
@FrancYescO  sono registrato, ma mi dice che non ho i permessi per entrare.

Volevo fare dei test, ho usato un Orange pi zero LTS + dvbt usb + tvheadend + oscam, e volevo provare se riuscivo a far andare anche freecsD =)

Grazie

**Comment by FrancYescO** [comment]
Forse sei bannato, sinceramente non saprei devi chiedere li.
________________________________

**Comment by miazza99** [comment]
Ogni tanto si fa fatica ad accedere a quel sito. I DNS non sempre lo permettono. Da qualche giorno non riesco a visitare il forum.

**Comment by formatta2003** [comment]
ciao a tutti magari voi potete aiurarmi

grazie a un amico che aveva aiutato un po di anni fa ho messo freecsd su uno zgemma h2
adesso ho cambiato il decodere ho preso octagon sf8008 e ho openatv 6.4 ma non so da dove cominciare per installare oscam e freecsd..... non ho piu possibilita di farmi aiutare dall'amico.... mi date qualche dritta per favore... grazieeeeee
